### ISSUE TITLE
Do we want separately dereferencable individual Activity descriptions?

### ISSUE THREAD

**Issue by zimeon** [LD4/entity_metadata_management#102]
Separately dereferenceable Activity description aren't required by the Activity Streams specification and seems just to create a multitude of small documents that are redundant because the information is already in the Change Set. 

I see that LC Change Sets do not include separately dereferenceable links for each activity (seem to include some bnode ids but that is just clutter in the serialization, not for dereferencing)

**Comment by sfolsom** [comment]
Agreement to remove this requirement among the group.
