### ISSUE TITLE
Clarify two instances of "... MUST ... if ... "

### ISSUE THREAD

**Issue by zimeon** [LD4/entity_metadata_management#12]
There are two instances of _"Each Entity Change Notification MUST use the partOf property if referring back to the Change Set that includes this notification. "_  in the definitions in the use of `partOf` in 
https://ld4.github.io/entity_metadata_management/api/0.1/recommendations.html#entity-change-notification and https://ld4.github.io/entity_metadata_management/api/0.1/recommendations.html#new-entity

I'm not quite sure what the intended meaning is, perhaps:
* The `partOf` property MUST be present and MUST refer back to the change set that includes the notification
* The `partOf` property MAY be used to refer back to the change set that includes the notification

I suspect the former is intended?

**Comment by sfolsom** [comment]
I think what is meant is... you're not required to link back to the ChangeSet, but *if* you do... you MUST to use partOf.

**Comment by zimeon** [comment]
I think that is the second case then: The partOf property MAY be used to refer back to the change set that includes the notification

I don't think it makes sense to try to forbid linking back with some other property, that might be a meaningful extension for some other reason but such information would be ignored by a client following the API.

**Comment by zimeon** [comment]
@sfolsom - Thinking about this a little more, perhaps it is also intended that `partOf` should not be used for anything else? If that is the case then maybe the text could read:

> A Entity Change Notification MAY use the `partOf` property to refer back to the Change Set that includes the notification. The `partOf` property MUST NOT be used for any other purpose.

**Comment by sfolsom** [comment]
Right, given the open world assumption and `partOf` domain and ranges, we wouldn't want unintended meanings in our implementations.

**Comment by sfolsom** [comment]
@eslao could you take a look at this, given your background with ontologies/data models?

**Comment by sfolsom** [comment]
If @eslao doesn't have objections, based on 2022-08-29 discussions, @sfolsom will merge this request.

**Comment by eslao** [comment]
No objections! Sorry for the hold up.

**Comment by zimeon** [comment]
https://github.com/LD4/entity_metadata_management/pull/20 was merged. Closing.
