### ISSUE TITLE
Correct "Entity Metadata Provides" to "Entity Metadata Providers" 

### ISSUE THREAD

**Issue by greeve** [LD4/entity_metadata_management#14]
There is a typo in the Objectives and Scope section where "Entity Metadata Provides" should read "Entity Metadata Providers". 

https://ld4.github.io/entity_metadata_management/api/0.1/recommendations.html#objectives-and-scope

**Comment by sfolsom** [comment]
Fixed in https://github.com/LD4/entity_metadata_management/pull/21
