### ISSUE TITLE
One @context or two?

### ISSUE THREAD

**Issue by zimeon** [LD4/entity_metadata_management#30]
PR #29 fixes the immediate part of issue #11. While working on this I notice that the current draft EMM context https://ld4.github.io/entity_metadata_management/api/0.1/context.json already includes the Activity Streams (AS) context. Thus, while the corrected examples now have the following context definition:

```
"@context": [
    "https://www.w3.org/ns/activitystreams",
    "https://ld4.github.io/entity_metadata_management/api/0.1/context.json"
  ],
```

the explicit inclusion of `https://www.w3.org/ns/activitystreams` is unnecessary. The examples would have exactly the same expansion if the context definition were simply:

```
"@context": "https://ld4.github.io/entity_metadata_management/api/0.1/context.json"
```

Should we use this simpler form or is it useful to directly reference the AS context?

**Comment by sfolsom** [comment]
I lean towards the simpler form. While it's the base of our recommendation, I thinks it's good to treat "external" vocabularies similarly. I hope we make clear that our recommendation leans heavily on/extends AS.

**Comment by sfolsom** [comment]
I'll merge PR 29, then assign @zimeon to create a separate PR for the simpler form based on 2022-08-29 meeting discussions.
