### ISSUE TITLE
Entity Change Notification or Activity?

### ISSUE THREAD

**Issue by zimeon** [LD4/entity_metadata_management#31]
There is a comment in the draft: **To tie the language we are using closer to the Activity Stream, should we rename Entity Change Notification to Entity Change Activity?**

I think it would make sense to change the terminology to use "Entity Change Activity" because:
  1. aligns with Activity Streams where the change is described as an AS `Activity`
  2. to me notification implies a push style of update, whereas at the moment we are describing a publication method (pull) and explicitly rule [push notifications out-of-scope](https://ld4.github.io/entity_metadata_management/api/0.1/recommendations.html#objectives-and-scope)

**Comment by sfolsom** [comment]
Addressed with https://github.com/LD4/entity_metadata_management/pull/58
