### ISSUE TITLE
Descending date order q

### ISSUE THREAD

**Issue by kefo** [LD4/entity_metadata_management#34]
> All changes within a Change Set and, if applicable, across Change Sets *MUST be sorted in date-time order in the orderedItems property with the earliest change in the set appearing first and most recent change in the set appearing last.*

From https://ld4.github.io/entity_metadata_management/api/0.1/recommendations.html#change-set

There are really two MUSTs here.  It MUST be sorted in date-time order and it MUST be in ascending date order.  I'm not sure I have a problem with the first MUST, though it may be too restrictive over time(?), but the second would basically invalidate our stuff.

**Comment by kefo** [comment]
I think the wording does what it needs to do.  I'm not entirely clear why we are even stating a preference, however.

**Comment by sfolsom** [comment]
Based on today's discussion, @eichmann has agreed to reflect what it means to allow for either ascending or descending order, noting what this means for rdf_patch. Related, we need to clear up any potential confusion around order assuming completeness (or a lack thereof).

**Comment by sfolsom** [comment]
@eichmann see this related unmerged pull request: https://github.com/LD4/entity_metadata_management/pull/16

**Comment by sfolsom** [comment]
When we update the recommendations to allow for ascending or descending order, we need to make sure to update/remove the last sentence in the first paragraph of 3.2, https://ld4.github.io/entity_metadata_management/api/0.1/recommendations.html#change-set.

**Comment by zimeon** [comment]
We have agreed that activities MUST be time ordered but can be either way round. Reflected in https://ld4.github.io/entity_metadata_management/0.1/#change-set with:
> The Activities within a Change Set MUST be sorted in date-time order in the orderedItems array. The Activities MAY be in ascending or descending order, but the order MUST be consistent within the Collection.

DONE
