### ISSUE TITLE
Which date properties should be used and how

### ISSUE THREAD

**Issue by zimeon** [LD4/entity_metadata_management#39]
Notes from to-dos in the draft:
* decide on recommendations for date handling (options: startTime, endTime, updated, published)
* Add discussion and reasoning for when to use each type of date. Still need to determine our recommendations around dates.
  * [endTime](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-endtime) property definition  
  * [startTime](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-starttime) property definition
  * [published](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-published) property definition
  * [updated](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-updated) property definition
  * [deleted](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-deleted) property definition

**Comment by zimeon** [comment]
Have separated out discussion of `updated` on Activity objects in #59.

See also #55 for discussion of `first` and `last` where these used to be objects with `published` in the examples. Discussion now allow these to be simple references to the `first` and `last` pages rather than inline objects.

**Comment by sfolsom** [comment]
Per 10/24 meeting: If we use published date for the activity, and updated for the actual object... it would allow for us to be more specific about when something was published vs. when the thing changed (if needed).

**Comment by zimeon** [comment]
We have decided on:
* `published` for Activities
* `updated` for Objects
* and will stay silent regarding dates on Change Sets and Entry Points (can follow Activity Streams but a specific usage is not needed for our use case)
