### ISSUE TITLE
The value MUST be a JSON object...

### ISSUE THREAD

**Issue by kefo** [LD4/entity_metadata_management#55]
> The Entry Point MUST have a first property. The value MUST be a JSON object, with the id and type properties. The value of the id property 

See:  https://ld4.github.io/entity_metadata_management/api/0.1/recommendations.html#entry-point-first

This is stipulating that the value of `first` be a JSON object, even though a resource reference is sufficient/acceptable.  The ActivityStreams documentation shows that this can be an Object or a URI reference:  https://www.w3.org/TR/activitystreams-vocabulary/#dfn-first

This has processing ramifications/expectations.  This shows up, too, with `last`.

**Comment by sfolsom** [comment]
We agreed to remove the requirement for first and last. TODO: @sfolsom remove the requirement for first and last.

**Comment by sfolsom** [comment]
Addressed in https://github.com/LD4/entity_metadata_management/pull/62
