### ISSUE TITLE
What are the requirements for a datestamp on Activity objects?

### ISSUE THREAD

**Issue by zimeon** [LD4/entity_metadata_management#59]
Currently, in every Activity example (e.g. "EXAMPLE Entity Change Notification for Create" in https://ld4.github.io/entity_metadata_management/api/0.1/recommendations.html#new-entity) we use the [`updated` property](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-updated) to indicate the datestamp of the underlying change. However, we do not require this nor describe its use. The use of `updated` is not required by Activity Streams.

**Comment by zimeon** [comment]
I think we need some consistent notion of datestamp to make sure that Activity objects are processed in the correct order and so that a harvester can restart from some point in the stream of updates. I think mandating `updated` would make sense.

**Comment by sfolsom** [comment]
FIXED with https://github.com/LD4/entity_metadata_management/pull/61
