### ISSUE TITLE
Use of "orderedItem" property to nest Activities

### ISSUE THREAD

**Issue by sfolsom** [LD4/entity_metadata_management#9]
It's hard (for me) to tell what is happening in the 3.2 Deprecate activity examples. There seems to be nested Create and Update Activities within a Deprecated Activity. It’s unclear how they are related.

According to https://www.w3.org/TR/activitystreams-core/#collections, orderedItem seems to be for OrderedCollections and OrderedCollectionPages, not for nesting Activities within Activities. This is maybe illustrated in how 3.2 example has 2 totalItems, but the stream actually has 4 activities.

Do we need to nest related activities if we can just order them in a single stream? According to the documentation activities "MUST be sorted in date-time order in the orderedItems property with the earliest change in the set appearing first and most recent change in the set appearing last." This suggest to me we don't need to nest the activities.

E.g.

"orderedItems": [
    {
      "type": "Create",
      "object": "http://example.org/Milk"
    },
    {
      "type": "Deprecate",
      "object": "http://example.org/milk"
      “seeInstead”: "http://example.org/Milk"
    },
    {
      "type": "Create",
      "object": "http://example.org/BovineMilk"
    },
    {
      "type": "Create",
      "object": "http://example.org/CowMilk"
    },
    {
      "type": "Create",
      "object": "http://example.org/Science"
    }
  ]

**Comment by zimeon** [comment]
Propose `close won't fix` -- I think we have decided not to used nested or otherwise tightly coupled activities, see also #68
