### ISSUE TITLE
Replacement for deprecated concepts - Adding "Add" as a possibility?

### ISSUE THREAD

**Issue by aisaac** [LD4/entity_metadata_management#93]
The current spec says: 
[
An entity that has been deprecated SHOULD have an [Entity Change Activity](https://ld4.github.io/entity_metadata_management/0.1/#entity-change-activity) with the type Deprecate. The Deprecate activity MUST be implemented as either a single activity (when the entity that is replacing the deprecated entity already exists, or if the deprecated entity is not replaced), or two activities a Create activity for the replacement entity, and an Deprecate activity for the deprecated entity.
]

Could a deprecated entity be replaced by an entity that's been (re-)added into the entry point? In this case the text above should allow to use an Add activity, I suppose

**Comment by zimeon** [comment]
I wonder whether there could be Update as well? Perhaps an existing term is broadened to include within its scope something that has been Deprecated? I think we should be quite open-ended as to what is possible alongside a Deprecate (also noting that there may be multiple per #95)

**Comment by sfolsom** [comment]
Because we're already saying, "An entity that has been deprecated SHOULD have an [Entity Change Activity](https://ld4.github.io/entity_metadata_management/0.1/#entity-change-activity) with the type Deprecate." I think we should change the next sentence to "The Deprecate activity can be implemented as a single activity (when the entity that is replacing the deprecated entity/entities already exists, or if the deprecated entity is not replaced). If the Deprecate activity is replaced by one or more entities, a combination of Create, Update, and Add activities SHOULD also be used (as appropriate) for the replacement entity."

**Comment by zimeon** [comment]
:+1: on the above except I would not include the RFC word SHOULD because it is not enforcable

**Comment by zimeon** [comment]
Current spec text is a little different from that in this issue:

> Deprecation indicates that an existing entity in the authority has been updated to reflect that it should no longer be used though the URI remains dereferencable reflecting the deprecation. Whenever possible, the entity description should indicate which entity or entities should be used instead.
> 
> There are two common scenarios. In the first, the replacement entity or entities already exist and the deprecation updates the deprecated entity only. In the second scenario, the replacement entity or entities do not exist prior to the deprecation. In this case, the replacement entity or entities are created and the status of the original entity is changed to deprecrated.
> 
> An entity that has been deprecated SHOULD have an [Entity Change Activity](https://ld4.github.io/entity_metadata_management/0.1/#entity-change-activity) with the type Deprecate. The two scenarios are implemented as follows:
> 
> * A single Deprecate activity when the entity that is replacing the deprecated entity already exists, or if the deprecated entity is not replaced.
> * A Deprecate activity for the deprecated entity, and one or more Create activities for the replacement entity or entities. In all cases, it is expected that the consumer will dereference the deprecated entity URI to obtain the updated entity description, including whether it was replaced.
