### ISSUE TITLE
Cardinality of replacements

### ISSUE THREAD

**Issue by aisaac** [LD4/entity_metadata_management#95]
The current spec for `Deprecate` seems to strongly hint there can be only one entity to replace a deprecated entity. Can't this be several entities? In which case the spec should probably mention that there can be several `Create` (or `Add`, cf [issue 93](https://github.com/LD4/entity_metadata_management/issues/93)) activities next to the `Deprecate` one.

**Comment by zimeon** [comment]
I agree, we should allow the possibility of multiple activities related to a Deprecate

**Comment by sfolsom** [comment]
It was never our intention to say an entity could only be replaced by one entity, e.g. Splits.
