### ISSUE TITLE
It is not possible to create an Entry Point before a Change Set

### ISSUE THREAD

**Issue by zimeon** [LD4/entity_metadata_management#99]
The specification says an Entry Point _MUST_ have `first` and `last` properties linking to a Change Set. Thus there has to be a Change Set before an Entry Point is created... which is an odd requirement for the startup case

**Comment by zimeon** [comment]
Agreement in call that we are OK to have Entry Point requiring a Change Set. Need to check that section 6 doesn't say anything that assumes otherwise.

**Comment by zimeon** [comment]
What about the possible use case of an Entry Point with just a full data dump? That seems a valid use case of providing a machine readable link to the last dump (even though its is not on our list) which would not have `first` and `last`:

```
{
  "@context": "https://ld4.github.io/entity_metadata_management/0.1/context.json",
  "summary": "My Authority - Entry Point",
  "type": "OrderedCollection",
  "id": "https://data.my.authority/entry-point",
  "url": "https://my.authority/2021-01-01/full_download",
}
```

I think `first` and `last` should become SHOULD.

**Comment by sfolsom** [comment]
That makes sense to me. @eslao, @nancyjean, @kefo, @eichmann, @mixterj... thoughts?

**Comment by sfolsom** [comment]
Another option might be that if the Entry Point has one or more Change Sets, then it must have a first and last.

**Comment by zimeon** [comment]
I find the pattern "If _something_ then _MUST_ _something-else_" problematic because it looks like a requirement but then it isn't when _something_ is a choice. I'd prefer to go with language along the lines of what `first` and `last` do:
* The Entry Point _SHOULD_ have a `first` property to indicate the first Change Set in this Entry Point for the Entity Collection. 
* If present, the value _MUST_ be ....details....
